# Generated by Django 2.2 on 2021-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcid', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('colabs', models.TextField(default=0)),
            ],
        ),
    ]
