# Generated by Django 2.2 on 2021-08-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='dcid',
            new_name='doc_id',
        ),
    ]
